# Generated by Django 6.0.1 on 2026-01-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_remove_tasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='session_id',
            field=models.CharField(default='A11105', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
